### ISSUE TITLE
LED's Util

### ISSUE THREAD

**Issue by chadr03** [LHSPantherbots/2024-Swerve-Base#9]
I think to make the LED's more usable and less likely to cause issues we should make a public global robot state variable in our utils class.  Then make an LED's command that uses a logic or case select to pick the LED color.

Example

-Default - Panther Streak
-State "intake" - green pulse
-State "intake & isNoteDetected - orange pulse (I think a jostick rumble would be a good add here too)
-State isNoteDetected - orange
-State robotCentric - Rambow
-State launchSpinning - Blue
-Stake target acquired - Red - 

I would almost think the lower down the list the higher the priority.

**Comment by codytrey** [comment]
@itsme-hayden  can you work on this issue?

**Comment by codytrey** [comment]
fixed by latest merge
